
import React, { useState, useRef } from 'react';
import { usePlanner } from '../context';
import { Plus, CheckSquare, TrendingUp, Camera, Clock, X, Check, Copy, Send, Trash2, BarChart2, List } from 'lucide-react';
import { BarChart, Bar, XAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { Report, ReportMetric, Task } from '../types';

const toBase64 = (file: File) => new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = error => reject(error);
});

const Reports: React.FC = () => {
  const { reports, addReport, currentUser, getCompletedTasksForToday } = usePlanner();
  const [isModalOpen, setIsModalOpen] = useState(false);
  
  // Form State
  const [content, setContent] = useState('');
  const [startWork, setStartWork] = useState('10:00');
  const [endWork, setEndWork] = useState('19:00');
  
  // Dynamic Metrics State
  const [metrics, setMetrics] = useState<ReportMetric[]>([]);
  
  const [photos, setPhotos] = useState<string[]>([]);
  
  // Task Selection State
  const [availableTasks, setAvailableTasks] = useState<Task[]>([]);
  const [selectedTaskIds, setSelectedTaskIds] = useState<string[]>([]);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Filter logic
  const visibleReports = currentUser.role === 'OWNER' 
    ? reports 
    : reports.filter(r => r.userName === currentUser.name);

  const openModal = () => {
      setAvailableTasks(getCompletedTasksForToday());
      setSelectedTaskIds([]); 
      setMetrics([]); // Start fresh
      setIsModalOpen(true);
  };

  const closeModal = () => {
      setIsModalOpen(false);
      setContent('');
      setMetrics([]);
      setPhotos([]);
      setStartWork('10:00');
      setEndWork('19:00');
      setAvailableTasks([]);
      setSelectedTaskIds([]);
  };

  // --- Metrics Handlers ---
  const addMetric = (presetLabel?: string) => {
      const newMetric: ReportMetric = {
          id: `m-${Date.now()}-${Math.random()}`,
          label: presetLabel || '',
          value: 0
      };
      setMetrics([...metrics, newMetric]);
  };

  const removeMetric = (id: string) => {
      setMetrics(metrics.filter(m => m.id !== id));
  };

  const updateMetricValue = (id: string, val: number) => {
      setMetrics(metrics.map(m => m.id === id ? { ...m, value: val } : m));
  };

  const updateMetricLabel = (id: string, label: string) => {
      setMetrics(metrics.map(m => m.id === id ? { ...m, label } : m));
  };

  const handleSubmit = (e: React.FormEvent) => {
      e.preventDefault();
      
      // Get titles of selected tasks
      const selectedTaskTitles = availableTasks
          .filter(t => selectedTaskIds.includes(t.id))
          .map(t => t.title);

      // Filter out empty metrics
      const validMetrics = metrics.filter(m => m.label.trim() !== '');

      const report: Report = {
          id: `r-${Date.now()}`,
          userId: currentUser.role,
          userName: currentUser.name,
          date: new Date().toLocaleDateString('ru-RU', {day: 'numeric', month: 'long', year: 'numeric'}),
          content,
          type: 'Ежедневный отчет',
          workingHours: { start: startWork, end: endWork },
          metrics: validMetrics,
          images: photos,
          autoGeneratedTasks: selectedTaskTitles
      };

      addReport(report);
      closeModal();
  };

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
      if (e.target.files && e.target.files[0]) {
          const base64 = await toBase64(e.target.files[0]);
          setPhotos(prev => [...prev, base64]);
      }
  };

  const removeImage = (index: number) => {
      setPhotos(prev => prev.filter((_, i) => i !== index));
  };

  const toggleTaskSelection = (taskId: string) => {
      setSelectedTaskIds(prev => 
          prev.includes(taskId) 
              ? prev.filter(id => id !== taskId) 
              : [...prev, taskId]
      );
  };

  const copyToClipboard = (report: Report) => {
      const lines = [
          `📝 Ежедневный отчет: ${report.userName}`,
          `📅 Дата: ${report.date}`,
          ``,
          `⏱️ Рабочее время: ${report.workingHours?.start || '--:--'} - ${report.workingHours?.end || '--:--'}`,
          ``
      ];

      if (report.metrics && report.metrics.length > 0) {
          lines.push(`📊 Показатели:`);
          report.metrics.forEach(m => {
              lines.push(`• ${m.label}: ${m.value}`);
          });
          lines.push(``);
      }

      if (report.autoGeneratedTasks && report.autoGeneratedTasks.length > 0) {
          lines.push(`✅ Выполненные задачи:`);
          report.autoGeneratedTasks.forEach(t => lines.push(`- ${t}`));
          lines.push(``);
      }

      if (report.content) {
          lines.push(`💬 Комментарий:`);
          lines.push(`${report.content}`);
      }

      const text = lines.join('\n');
      navigator.clipboard.writeText(text).then(() => {
          alert('Отчет скопирован в буфер обмена!');
      });
  };

  const getLast7DaysData = () => {
      const data = [];
      for (let i = 6; i >= 0; i--) {
          const d = new Date();
          d.setDate(d.getDate() - i);
          const dayStr = d.toLocaleDateString('ru-RU', { weekday: 'short' });
          const dateKey = d.toLocaleDateString('ru-RU', {day: 'numeric', month: 'long', year: 'numeric'}); 
          
          const relevantReports = reports.filter(r => r.date === dateKey);
          
          let value = 0;
          if (relevantReports.length > 0) {
              value = relevantReports.reduce((acc, r) => {
                  const daySum = r.metrics?.reduce((sum, m) => sum + (Number(m.value) || 0), 0) || 0;
                  return acc + daySum;
              }, 0);
          } else {
               // Filler data for visual
               const dateHash = dateKey.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
               value = (dateHash % 10) + 2; 
          }
          
          data.push({ day: dayStr, value }); 
      }
      return data;
  };

  const chartData = getLast7DaysData();

  return (
    <div className="space-y-6 p-2 max-w-4xl mx-auto">
        <div className="flex justify-between items-center">
            <div>
                <h2 className="text-3xl font-bold text-white">Отчеты</h2>
                <p className="text-neutral-500 text-sm">Сводка продуктивности</p>
            </div>
            <button onClick={openModal} className="bg-blue-500 hover:bg-blue-600 text-white px-5 py-2.5 rounded-full font-bold shadow-lg shadow-blue-900/20 transition-transform active:scale-95 flex items-center gap-2">
                <Plus size={18}/> Создать отчет
            </button>
        </div>

        {/* Analytics Chart */}
        <div className="ios-card p-6 rounded-[24px] flex flex-col md:flex-row items-end gap-8 bg-gradient-to-br from-[#1c1c1e] to-neutral-900 border border-white/5">
            <div className="flex-1 w-full">
                <h3 className="text-lg font-bold text-white mb-1 flex items-center gap-2"><TrendingUp size={18} className="text-blue-400"/> Активность</h3>
                <p className="text-xs text-neutral-500 mb-4">Общие показатели за 7 дней</p>
                <div className="h-32 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={chartData}>
                            <XAxis dataKey="day" stroke="#555" tick={{fill: '#555', fontSize: 10}} axisLine={false} tickLine={false} />
                            <Tooltip 
                                contentStyle={{backgroundColor: '#1c1c1e', borderRadius: '12px', border: 'none', fontSize: '12px'}} 
                                cursor={{fill: 'rgba(255,255,255,0.05)'}}
                            />
                            <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                                {chartData.map((entry, index) => (
                                    <Cell key={`cell-${index}`} fill={index === 6 ? '#3b82f6' : '#3f3f46'} />
                                ))}
                            </Bar>
                        </BarChart>
                    </ResponsiveContainer>
                </div>
            </div>
        </div>

        <div className="space-y-6">
            {visibleReports.map(report => (
                <div key={report.id} className="bg-[#1c1c1e] p-6 rounded-[32px] border border-white/5 max-w-2xl mx-auto shadow-2xl relative overflow-hidden animate-in fade-in slide-in-from-bottom-4">
                    {/* Header */}
                    <div className="flex items-center gap-4 mb-6 border-b border-white/5 pb-4">
                        <div className="w-12 h-12 rounded-full bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white shadow-lg text-sm font-bold">
                             {report.userName.slice(0,2).toUpperCase()}
                        </div>
                        <div>
                             <h4 className="text-lg font-bold text-white">{report.userName}</h4>
                             <p className="text-xs text-neutral-400 font-medium uppercase tracking-wider">{report.type}</p>
                        </div>
                        <div className="ml-auto text-right flex flex-col items-end gap-2">
                            <div className="text-sm text-white font-bold">{report.date}</div>
                            <button 
                                onClick={() => copyToClipboard(report)}
                                className="text-[10px] bg-white/10 hover:bg-white/20 text-white px-3 py-1.5 rounded-full flex items-center gap-1.5 transition-colors font-medium"
                                title="Скопировать текст для Telegram"
                            >
                                <Copy size={12} /> Copy
                            </button>
                        </div>
                    </div>

                    {/* Working Hours */}
                    {report.workingHours && (
                        <div className="mb-6 flex gap-3">
                            <div className="flex-1 bg-white/5 rounded-2xl p-3 flex items-center gap-3 border border-white/5">
                                <div className="p-2 bg-green-500/10 rounded-xl text-green-400"><Clock size={16}/></div>
                                <div>
                                    <p className="text-[10px] text-neutral-500 uppercase font-bold">Пришел</p>
                                    <p className="text-white font-mono font-bold">{report.workingHours.start}</p>
                                </div>
                            </div>
                            <div className="flex-1 bg-white/5 rounded-2xl p-3 flex items-center gap-3 border border-white/5">
                                <div className="p-2 bg-red-500/10 rounded-xl text-red-400"><Clock size={16}/></div>
                                <div>
                                    <p className="text-[10px] text-neutral-500 uppercase font-bold">Ушел</p>
                                    <p className="text-white font-mono font-bold">{report.workingHours.end}</p>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Dynamic Metrics Display */}
                    {report.metrics && report.metrics.length > 0 && (
                        <div className="mb-6">
                            <h5 className="text-xs font-bold text-neutral-500 uppercase mb-3 flex items-center gap-2">
                                <BarChart2 size={12}/> Показатели
                            </h5>
                            <div className="flex flex-wrap gap-3">
                                {report.metrics.map((m) => (
                                    <div key={m.id} className="bg-neutral-900/80 p-3 px-4 rounded-2xl border border-white/5 flex flex-col items-start min-w-[100px]">
                                        <p className="text-[10px] text-neutral-400 uppercase font-bold mb-1">{m.label}</p>
                                        <p className="text-xl font-bold text-white">{m.value}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Completed Tasks List */}
                    {report.autoGeneratedTasks && report.autoGeneratedTasks.length > 0 && (
                        <div className="mb-6 bg-neutral-900/30 p-4 rounded-2xl border border-white/5">
                            <p className="text-[10px] text-neutral-500 uppercase font-bold mb-3 flex items-center gap-2">
                                <CheckSquare size={12} className="text-blue-400"/> Выполненные задачи
                            </p>
                            <ul className="space-y-2">
                                {report.autoGeneratedTasks.map((taskTitle, idx) => (
                                    <li key={idx} className="text-xs text-neutral-300 flex items-start gap-2">
                                        <Check size={12} className="text-green-500 mt-0.5 shrink-0" />
                                        <span className="leading-snug">{taskTitle}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {/* Text Content */}
                    {report.content && (
                        <div className="mb-6">
                             <h5 className="text-xs font-bold text-neutral-500 uppercase mb-2">Комментарий</h5>
                             <div className="text-sm text-neutral-300 whitespace-pre-wrap leading-relaxed font-light bg-neutral-900/50 p-4 rounded-2xl border border-white/5">
                                {report.content}
                            </div>
                        </div>
                    )}

                    {/* Images */}
                    {report.images && report.images.length > 0 && (
                        <div className="grid grid-cols-3 gap-2">
                            {report.images.map((img, i) => (
                                <div key={i} className="aspect-square rounded-xl overflow-hidden border border-white/10 cursor-pointer hover:opacity-80 transition-opacity group relative">
                                    <img src={img} alt="Report attachment" className="w-full h-full object-cover" />
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            ))}
        </div>

        {/* --- REPORT CREATION MODAL --- */}
        {isModalOpen && (
            <div 
                className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 animate-in fade-in duration-200"
                onClick={(e) => { if (e.target === e.currentTarget) closeModal() }}
            >
                <div className="bg-[#1c1c1e] w-full max-w-lg p-0 rounded-[32px] shadow-2xl max-h-[90vh] overflow-hidden border border-white/10 flex flex-col">
                    <div className="p-6 border-b border-white/10 flex justify-between items-center bg-[#1c1c1e] z-10">
                        <div>
                             <h3 className="text-xl font-bold text-white">Новый отчет</h3>
                             <p className="text-xs text-neutral-500">{new Date().toLocaleDateString()}</p>
                        </div>
                        <button onClick={closeModal} className="p-2 bg-white/5 rounded-full hover:bg-white/10 transition-colors"><X size={20} className="text-neutral-400 hover:text-white"/></button>
                    </div>
                    
                    <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto custom-scrollbar p-6 space-y-8">
                        
                        {/* 1. Working Hours */}
                        <div>
                            <label className="text-xs text-neutral-500 uppercase font-bold mb-3 block flex items-center gap-2"><Clock size={12}/> Рабочее время</label>
                            <div className="flex gap-4">
                                <div className="flex-1 bg-neutral-900 rounded-xl p-3 border border-white/5 focus-within:border-blue-500 transition-colors">
                                    <span className="text-[10px] text-neutral-500 block mb-1">Пришел</span>
                                    <input type="time" value={startWork} onChange={e => setStartWork(e.target.value)} className="bg-transparent text-white font-mono outline-none w-full text-lg font-bold"/>
                                </div>
                                <div className="flex-1 bg-neutral-900 rounded-xl p-3 border border-white/5 focus-within:border-blue-500 transition-colors">
                                    <span className="text-[10px] text-neutral-500 block mb-1">Ушел</span>
                                    <input type="time" value={endWork} onChange={e => setEndWork(e.target.value)} className="bg-transparent text-white font-mono outline-none w-full text-lg font-bold"/>
                                </div>
                            </div>
                        </div>

                        {/* 2. Dynamic Metrics Builder */}
                        <div>
                            <div className="flex justify-between items-center mb-3">
                                <label className="text-xs text-neutral-500 uppercase font-bold flex items-center gap-2"><List size={12}/> Показатели</label>
                                <button type="button" onClick={() => addMetric('')} className="text-[10px] bg-blue-500 text-white px-3 py-1 rounded-full font-bold hover:bg-blue-400 transition-colors">
                                    + Добавить поле
                                </button>
                            </div>
                            
                            {/* Quick Preset Buttons */}
                            <div className="flex gap-2 mb-4 overflow-x-auto pb-2">
                                {['Отправлено', 'Упаковано', 'Возвраты', 'Звонки'].map(label => (
                                    <button 
                                        key={label}
                                        type="button" 
                                        onClick={() => addMetric(label)} 
                                        className="whitespace-nowrap px-3 py-1.5 rounded-lg bg-white/5 text-neutral-400 text-xs font-bold border border-white/5 hover:bg-white/10 hover:text-white transition-colors"
                                    >
                                        + {label}
                                    </button>
                                ))}
                            </div>

                            {/* Active Metrics List */}
                            <div className="space-y-3">
                                {metrics.map((metric) => (
                                    <div key={metric.id} className="flex items-center gap-3 bg-neutral-900 p-3 rounded-2xl border border-white/5 animate-in slide-in-from-left-2 duration-200 group">
                                        <div className="flex-1">
                                            <input 
                                                value={metric.label} 
                                                onChange={(e) => updateMetricLabel(metric.id, e.target.value)}
                                                className="bg-transparent text-xs text-neutral-400 font-bold uppercase w-full outline-none mb-1 placeholder-neutral-600"
                                                placeholder="НАЗВАНИЕ МЕТРИКИ"
                                            />
                                            <input 
                                                type="number"
                                                value={metric.value || ''}
                                                onChange={(e) => updateMetricValue(metric.id, Number(e.target.value))}
                                                className="bg-transparent text-white font-bold text-xl w-full outline-none placeholder-neutral-700"
                                                placeholder="0"
                                            />
                                        </div>
                                        <button 
                                            type="button" 
                                            onClick={() => removeMetric(metric.id)}
                                            className="w-8 h-8 rounded-full bg-white/5 hover:bg-red-500/20 text-neutral-500 hover:text-red-500 flex items-center justify-center transition-colors opacity-0 group-hover:opacity-100"
                                        >
                                            <Trash2 size={14}/>
                                        </button>
                                    </div>
                                ))}
                                {metrics.length === 0 && (
                                    <div className="text-center py-6 bg-white/[0.02] rounded-2xl border border-dashed border-white/5 text-xs text-neutral-600">
                                        Нет показателей. Добавьте свои метрики выше.
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* 3. Task Selection */}
                        {availableTasks.length > 0 && (
                            <div>
                                <label className="text-xs text-neutral-500 uppercase font-bold mb-3 flex items-center justify-between">
                                    <span className="flex items-center gap-2"><CheckSquare size={12}/> Задачи за сегодня</span>
                                    <span className="text-[10px] font-normal normal-case opacity-70 bg-white/5 px-2 py-0.5 rounded-full">{selectedTaskIds.length} выбрано</span>
                                </label>
                                <div className="bg-neutral-900 rounded-2xl border border-white/5 overflow-hidden">
                                    {availableTasks.map(task => (
                                        <div 
                                            key={task.id} 
                                            onClick={() => toggleTaskSelection(task.id)}
                                            className={`p-3 border-b border-white/5 last:border-0 flex items-center gap-3 cursor-pointer transition-colors ${selectedTaskIds.includes(task.id) ? 'bg-blue-500/10' : 'hover:bg-white/5'}`}
                                        >
                                            <div className={`w-5 h-5 rounded-md border flex-shrink-0 flex items-center justify-center transition-all ${selectedTaskIds.includes(task.id) ? 'bg-blue-500 border-blue-500' : 'border-neutral-600 bg-neutral-800'}`}>
                                                {selectedTaskIds.includes(task.id) && <Check size={12} className="text-white stroke-[3]" />}
                                            </div>
                                            <div className="min-w-0">
                                                <p className={`text-xs leading-tight truncate ${selectedTaskIds.includes(task.id) ? 'text-white font-medium' : 'text-neutral-400'}`}>{task.title}</p>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* 4. Text Content */}
                        <div>
                            <label className="text-xs text-neutral-500 uppercase font-bold mb-3 block">Комментарий</label>
                            <textarea 
                                value={content}
                                onChange={e => setContent(e.target.value)}
                                className="w-full h-32 bg-neutral-900 rounded-2xl p-4 text-white outline-none resize-none border border-white/5 focus:border-blue-500/50 text-sm placeholder-neutral-700 transition-colors leading-relaxed"
                                placeholder="Опишите, что было сделано..."
                            />
                        </div>

                        {/* 5. Photos */}
                        <div>
                            <label className="text-xs text-neutral-500 uppercase font-bold mb-3 block flex items-center gap-2"><Camera size={12}/> Фотоотчет</label>
                            <div className="flex flex-wrap gap-2">
                                {photos.map((img, i) => (
                                    <div key={i} className="w-20 h-20 rounded-xl overflow-hidden relative group border border-white/10">
                                        <img src={img} className="w-full h-full object-cover" />
                                        <button type="button" onClick={() => removeImage(i)} className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity text-white">
                                            <X size={16}/>
                                        </button>
                                    </div>
                                ))}
                                <button 
                                    type="button"
                                    onClick={() => fileInputRef.current?.click()}
                                    className="w-20 h-20 rounded-xl bg-neutral-900 border border-dashed border-white/20 flex flex-col items-center justify-center text-neutral-500 hover:text-white hover:border-white/40 hover:bg-white/5 transition-all group"
                                >
                                    <Camera size={24} className="mb-1 group-hover:scale-110 transition-transform"/>
                                    <span className="text-[9px]">Добавить</span>
                                </button>
                                <input type="file" ref={fileInputRef} className="hidden" accept="image/*" onChange={handleImageUpload} />
                            </div>
                        </div>

                    </form>
                    
                    <div className="p-6 border-t border-white/10 bg-[#1c1c1e]">
                        <button onClick={handleSubmit} className="w-full py-4 rounded-2xl bg-blue-600 text-white font-bold text-lg shadow-lg shadow-blue-900/20 hover:bg-blue-500 transition-all active:scale-95 flex items-center justify-center gap-2">
                            <Send size={18} /> Отправить отчет
                        </button>
                    </div>
                </div>
            </div>
        )}
    </div>
  );
};

export default Reports;